#!/bin/sh

# There are some non-unique mac-addresses assigned to LAN in early 2023,
# use the wifi mac for them instead. bad-unique-id must report it as well.

if [ -n "$(bad-unique-id)" ]; then
    dev=*wifi0
else
    dev=eth0
fi

tr -d: </sys/class/net/$dev/address
